# Generated by Django 3.1.7 on 2021-03-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0003_health_institution_health_professional'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_institution',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
