# Generated by Django 3.1.7 on 2021-03-31 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0004_health_institution_is_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health_institution',
            name='is_validated',
        ),
    ]
