# Generated by Django 3.1.7 on 2021-04-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0006_health_professional_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health_institution',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='health_professional',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
