# Generated by Django 3.1.7 on 2021-04-25 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0008_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
