# Generated by Django 3.1.7 on 2021-04-27 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0010_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_institution',
            name='followed_by',
            field=models.ManyToManyField(to='net.Health_Professional'),
        ),
        migrations.AddField(
            model_name='health_professional',
            name='followed_by',
            field=models.ManyToManyField(to='net.Health_Professional'),
        ),
    ]
