# Generated by Django 3.1.7 on 2021-04-28 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0012_auto_20210428_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health_institution',
            name='followed_by',
        ),
        migrations.RemoveField(
            model_name='health_professional',
            name='followed_by',
        ),
        migrations.AddField(
            model_name='health_professional',
            name='following_inst',
            field=models.ManyToManyField(related_name='health_professional_following', to='net.Health_Institution'),
        ),
        migrations.AddField(
            model_name='health_professional',
            name='following_prof',
            field=models.ManyToManyField(related_name='health_professional_following', to='net.Health_Professional'),
        ),
        migrations.AlterField(
            model_name='health_professional',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='net.health_institution'),
        ),
    ]
