# Generated by Django 3.1.7 on 2021-04-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0015_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
