# Generated by Django 3.1.7 on 2021-04-28 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('net', '0018_auto_20210428_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de publicação'),
            preserve_default=False,
        ),
    ]
